@istest
public class vehicleTrigger_test {
    
    public  testmethod  static void testmethod1()
    {
       Vehicle__c v = new Vehicle__c();
        list<Vehicle__c> newv = new list <Vehicle__c>();
        vehicleChild__c vc =new vehicleChild__c();
        list<vehicleChild__c>newvc  = new list<vehicleChild__c>();
        for(integer i =0;i<1000;i++)
        {
            
        }
        
        
    }

}